stages:
    - compile
    - container-build

jekyll-build:
    stage: compile
    image: jekyll/builder
    tags:
        - docker
    script:
        - cd src/
        - jekyll clean
        - jekyll build
    artifacts:
        paths: 
            - src/_site/
        name: "webroot"

container-build:
    stage: container-build
    tags:
        - docker-builder
    dependencies:
        - jekyll-build
    before_script:
        - docker info
        - docker login -u cicd-container -p chrHyQZ_gesKrFMJZZB9 gitlab.vj.home:5050
    script:
        - docker build -t "gitlab.vj.home:5050/johannes/www-jmbfountain-de:${CI_BUILD_REF}" .
        - docker tag gitlab.vj.home:5050/johannes/www-jmbfountain-de:${CI_BUILD_REF} "gitlab.vj.home:5050/johannes/www-jmbfountain-de:latest"
        - docker push gitlab.vj.home:5050/johannes/www-jmbfountain-de:${CI_BUILD_REF}
        - docker push gitlab.vj.home:5050/johannes/www-jmbfountain-de:latest
