stages:
    - compile
    - container-build

jekyll-build:
    stage: compile
    image: jekyll/builder
    tags:
        - docker
    script:
        - cd src/
        - jekyll clean
        - jekyll build
    artifacts:
        paths: 
            - src/_site/
        name: "webroot"

container-build:
    stage: container-build
    tags:
        - docker-builder
    dependencies:
        - jekyll-build
    before_script:
        - unset cd
        - docker info
        - echo "$CI_DEPLOY_USER"
    script:
        - docker build -t gitlab.vj.home:5050/johannes/www-jmbfountain-de .
        - docker push gitlab.vj.home:5050/johannes/www-jmbfountain-de
