stages:
    - compile
    - container-build

jekyll-build:
    stage: compile
    image: jekyll:build
    script:
        - jekyll clean
        - jekyll build
    artifacts:
        paths: 
            - _site/
        name: "webroot"

container-build:
    stage: container-build
    image: docker:latest
    dependencies:
        - jekyll-build
    script:
        - docker login -u cicd-container -p chrHyQZ_gesKrFMJZZB9 gitlab.vj.home:5050
        - docker build -t "gitlab.vj.home:5050/johannes/www-jmbfountain-de:${CI_BUILD_REF}" .
        - docker tag gitlab.vj.home:5050/johannes/www-jmbfountain-de:${CI_BUILD_REF} "gitlab.vj.home:5050/johannes/www-jmbfountain-de:latest"
        - docker push gitlab.vj.home:5050/johannes/www-jmbfountain-de:${CI_BUILD_REF}
        - docker push gitlab.vj.home:5050/johannes/www-jmbfountain-de:latest
