title: JmbFountain
author:
  name: Johannes
  email: jmb@smx.de
description: > # this means to ignore newlines until "show_excerpts:"
  Website of Johannes, here I write about all sorts of stuff I usually do, along with random other stuff

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d-%H-%M"

  skin: dark

  # generate social links in footer
  social_links:
    twitter: jmbfountain
    github:  jmbfountain
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: 
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    gitlab:
     - username: johannes
       instance: www.jmbfountain.de/git/
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
